apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
data:
  # policy.csv는 사용자 정의 RBAC 정책과 역할 정의를 포함하는 파일입니다 (선택 사항).
  # 정책 규칙은 다음과 같은 형식입니다:
  #   p, subject, resource, action, object, effect
  # 역할 정의와 바인딩은 다음과 같은 형식입니다:
  #   g, subject, inherited-subject
  # 자세한 내용은 https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/rbac.md를 참조하세요.
  policy.csv: |
    # 'my-org:team-alpha' 그룹의 모든 구성원에게 'my-project'에서 앱을 동기화할 수 있는 권한 부여
    p, my-org:team-alpha, applications, sync, my-project/*, allow
    # 'my-org:team-beta'의 모든 구성원에게 관리자 권한 부여
    g, my-org:team-beta, role:admin

  # 최종 정책 csv를 구성하기 위해 이 configmap에 추가 항목을 제공할 수 있습니다.
  # 이 경우 키는 'policy.<임의의 문자열>.csv' 패턴을 따라야 합니다. Argo CD는 이 패턴을 찾는 모든 추가 정책을
  # 주요 정책('policy.csv') 아래에 연결합니다. 이는 Kustomize, Helm 등의 구성 관리 도구에서 정책을 구성할 때 유용합니다.
  policy.overlay.csv: |
    p, role:tester, applications, *, */*, allow
    p, role:tester, projects, *, *, allow
    g, my-org:team-qa, role:tester

  # policy.default는 Argo CD가 API 요청을 승인할 때 기본적으로 사용할 역할의 이름입니다 (선택 사항).
  # 생략되거나 비어 있으면, 사용자는 로그인할 수 있지만 앱, 프로젝트 등을 볼 수 없습니다.
  policy.default: role:readonly

