apiVersion: batch/v1
kind: Job
metadata:
  name: fetch-latest-image
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: fetch-latest-image
        image: amazonlinux
        command: ["/bin/bash", "-c"]
        args:
          - >
            yum install -y aws-cli jq;
            LATEST_IMAGE=$(aws ecr list-images --repository-name skylo-ecr --query 'sort_by(imageIds,&imagePushedAt)[-1].imageTag' --output text --region ap-northeast-2);
            kubectl create secret generic latest-image --from-literal=image=$LATEST_IMAGE --dry-run=client -o yaml | kubectl apply -f -
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: aws_access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: aws_secret_access_key
        - name: AWS_DEFAULT_REGION
          value: "ap-northeast-2"
      restartPolicy: OnFailure

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  namespace: default
spec:
  replicas: 4
  selector:
    matchLabels:
      app: was
  template:
    metadata:
      labels:
        app: was
    spec:
      containers:
      - name: was
        image: 058264317535.dkr.ecr.ap-northeast-2.amazonaws.com/skylo-ecr:server-$(LATEST_IMAGE)
        resources:
          limits:
            memory: "64Mi"
            cpu: "0.2"
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: aws-credentials
