apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web      
  template:
    metadata:
      labels:
        app: web       
    spec:
      containers:
      - name: web
      image: 058264317535.dkr.ecr.ap-northeast-2.amazonaws.com/skylo-ecr:webapp-f28508e91412ec436ae43c4c8564a23450751331
      resources:
        limits:
          memory: "64Mi"
          cpu: "0.2"
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: aws-credentials