apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp-application
spec:
  destination:
    name: ''
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: manifest/webapp
    repoURL: 'git@github.com:kosa-skylo/demo-repository.git'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true