apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: 058264317535.dkr.ecr.ap-northeast-2.amazonaws.com/skylo-ecr:server-63ca84eb0c758562d7bce846b9866b343d65d2e1
        resources:
          limits:
            memory: "64Mi"
            cpu: "0.2"
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: aws-credentials
        
