apiVersion: batch/v1
kind: Job
metadata:
  name: ecr-login-job
spec:
  template:
    spec:
      containers:
      - name: ecr-login
        image: amazon/aws-cli:latest
        command: ["sh", "-c"]
        args:
          - |
            apk add --no-cache curl && \
            curl -LO "https://dl.k8s.io/release/v1.25.0/bin/linux/amd64/kubectl" && \
            chmod +x ./kubectl && \
            mv ./kubectl /usr/local/bin/kubectl && \
            kubectl version --client && \
            PASSWORD=$(aws ecr get-login-password --region ap-northeast-2) && \
            kubectl create secret docker-registry ecr-secret \
              --docker-server=058264317535.dkr.ecr.ap-northeast-2.amazonaws.com \
              --docker-username=AWS \
              --docker-password=$PASSWORD \
              --dry-run=client -o yaml | kubectl apply -f -
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: aws_access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: aws_secret_access_key
      restartPolicy: Never


---
apiVersion: v1
kind: Pod
metadata:
  name: private-repo-test
  labels:
    name: private-repo-test
spec:
  containers:
  - name: private-repo-test
    image: 058264317535.dkr.ecr.ap-northeast-2.amazonaws.com/skylo-ecr:server-3cd48dd85d72488a6c63b7985770cf12adf193cf
    resources:
      limits:
        memory: "64Mi"
        cpu: "0.2"
    ports:
      - containerPort: 80
  imagePullSecrets:
  - name: ecr-secret