apiVersion: apps/v1
kind: Deployment
metadata:
  name: was-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: was
  template:
    metadata:
      labels:
        app: was
    spec:
      containers:
      - name: was
        image: 058264317535.dkr.ecr.ap-northeast-2.amazonaws.com/skylo-ecr:server-f28508e91412ec436ae43c4c8564a23450751331
        resources:
          limits:
            memory: "64Mi"
            cpu: "0.2"
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: aws-credentials
