apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: 058264317535.dkr.ecr.ap-northeast-2.amazonaws.com/skylo-ecr:server-f28508e91412ec436ae43c4c8564a23450751331
        resources:
          limits:
            memory: "64Mi"
            cpu: "0.2"
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: aws-credentials
        
