apiVersion: batch/v1
kind: Job
metadata:
  name: server-login-job
spec:
  template:
    spec:
      containers:
      - name: server-login
        image: amazon/aws-cli:latest
        command: ["sh", "-c"]
        args:
          - |
            PASSWORD=$(aws ecr get-login-password --region ap-northeast-2)
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: aws_access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: aws_secret_access_key
      restartPolicy: Never


---
apiVersion: v1
kind: Pod
metadata:
  name: private-repo-test
  labels:
    name: private-repo-test
spec:
  containers:
  - name: private-repo-test
    image: 058264317535.dkr.ecr.ap-northeast-2.amazonaws.com/skylo-ecr:server-63ca84eb0c758562d7bce846b9866b343d65d2e1


    resources:
      limits:
        memory: "64Mi"
        cpu: "0.2"
    ports:
      - containerPort: 80
  imagePullSecrets:
  - name: aws-credentials