name: Push Directory to Another Repository

on:
  push:
    branches:
      - main

jobs:
  push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Push to another repository
      uses: ./push to other
      with:
        source-directory: 'nginx'
        destination-github-username: 'kosa-skylo'
        destination-repository-name: 'demo-repository'
        user-email: 'hoseop4018@naver.com'
        user-name: 'sbgyhs'
        target-branch: 'main'
        commit-message: 'Update from origin repository'
        target-directory: ''
        create-target-branch-if-needed: true