name: Push to another repository

on:
  push:
    branches:
      - main
      


jobs:
  push-directory:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2

      - name: Push to another repository
        uses: ./path-to-your-action
        with:
          source-directory: 'nginx'
          destination-github-username: 'kosa-skylo'
          destination-repository-name: 'demo-repository'
          user-email: 'hoseop4018@naver.com'
          user-name: 'sbgyhs'
          commit-message: 'Update from ${{ github.repository }}@${{ github.sha }}'
          target-branch: 'main'
          create-target-branch-if-needed: true
