name: Push Directory to Another Repository

on:
  push:
    branches:
      - main

env:
  API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}



jobs:
  push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up git
      run: |
        git config --global user.email "${{ secrets.USER_EMAIL }}"
        git config --global user.name "${{ secrets.USER_NAME }}"
      
    - name: Push to another repository
      uses: ./push to other
      with:
        source-directory: 'manifest'
        destination-github-username: 'kosa-skylo'
        destination-repository-name: 'demo-repository'
        user-email: 'hoseop4018@naver.com'
        user-name: 'sbgyhs'
        target-branch: 'main'
        commit-message: 'Update from origin repository'
        target-directory: 'manifest'
        create-target-branch-if-needed: true

        