name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # 직접 지역 값을 설정

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: us-east-1  # 직접 지역 값을 설정

      - name: Build and Push Docker Images
        run: |
          # Debug: List all Dockerfile.* files
          echo "Listing Dockerfile.* files:"
          find "Collection of Dockerfiles" -type f -name 'Dockerfile.*'
          
          # Process each Dockerfile
          for DOCKERFILE in $(find "Collection of Dockerfiles" -type f -name 'Dockerfile.*'); do
            # Debug: Print the Dockerfile path
            echo "Processing Dockerfile: $DOCKERFILE"
            
            # Extract the base name of the Dockerfile to use as the image tag
            BASE_NAME=$(basename "$DOCKERFILE")
            IMAGE_NAME="${BASE_NAME#Dockerfile.}"
            
            # Debug: Print image name and tag
            echo "Base name: $BASE_NAME"
            echo "Image name: $IMAGE_NAME"
            
            # Build the Docker image
            docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_NAME-$IMAGE_TAG -f "$DOCKERFILE" .
            
            # Push the Docker image to ECR
            docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_NAME-$IMAGE_TAG
            
            # Optionally, set output variable for subsequent steps
            echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_NAME-$IMAGE_TAG" >> $GITHUB_ENV
          done

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ECR_REGISTRY: "058264317535.dkr.ecr.us-east-1.amazonaws.com"  # ECR 레지스트리 URL을 코드에 직접 포함
      ECR_REPOSITORY: "skylo-ecr" 
      IMAGE_TAG: ${{ github.sha }}